# Generated by Django 4.2.13 on 2024-07-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JWTToken",
            fields=[
                ("token_id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_blacklisted", models.BooleanField(default=False)),
            ],
        ),
    ]
