# Generated by Django 5.0.6 on 2024-07-11 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jwttoken",
            name="is_blacklisted",
        ),
    ]
