# Generated by Django 5.0.6 on 2024-07-12 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authen", "0002_remove_jwttoken_is_blacklisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="jwttoken",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
    ]
