# Generated by Django 5.0.7 on 2024-07-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_device_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
