# Generated by Django 5.0.7 on 2024-07-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_mac_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_number',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
