# Generated by Django 5.0.6 on 2024-07-27 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_alter_warehouse_warehouse_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="assigned_user",
        ),
        migrations.AddField(
            model_name="device",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
