# Generated by Django 5.0.7 on 2024-08-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_location_remove_device_location_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='Shipment',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
