# Generated by Django 5.0.7 on 2024-07-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_groups_user_is_superuser_user_last_login_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
